## HW1 四資四乙 3B232076-陳韻如

神經網路架構如下：

- 輸入層：6 個神經元
- 第一隱藏層：5個神經元，使用Relu
- 第二隱藏層：4個神經元，使用Relu
- 第三隱藏層：4個神經元，使用Sigmoid
- 輸出層：3個神經元，使用Softmax

In [35]:
import numpy as np

輸入資料：

因為輸入層有 6 個神經元，所以輸入資料 x 需要包含 6 個特徵值。
這裡使用以下數值作為輸入資料：

x = [0.5, 0.8, 0.3, 0.6, 0.2, 0.9]

因此 x 的陣列形狀為：(6,)

In [36]:
# 輸入資料x，共有6個特徵值
x = np.array([0.5, 0.8, 0.3, 0.6, 0.2, 0.9])

print("x =", x)
print("x 的形狀 =", x.shape)

x = [0.5 0.8 0.3 0.6 0.2 0.9]
x 的形狀 = (6,)


## 第一隱藏層

第一隱藏層共有 5 個神經元，激發函數使用 Relu。

因為輸入層有 6 個神經元，因此：W1 的形狀為：(6, 5)

W1 共有：6 × 5 = 30 個參數

偏值 b1 有 5 個：(5,)

因此第一隱藏層共有：30 + 5 = 35 個參數。

In [37]:
# 第一隱藏層
# 輸入6個神經元，輸出5個神經元

W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.2, 0.3, 0.4, 0.5, 0.1],
    [0.3, 0.4, 0.5, 0.1, 0.2],
    [0.4, 0.5, 0.1, 0.2, 0.3],
    [0.5, 0.1, 0.2, 0.3, 0.4],
    [0.1, 0.3, 0.5, 0.2, 0.4]
])

b1 = np.array([0.1, 0.2, 0.1, 0.2, 0.1])

print("W1 =")
print(W1)
print("W1 shape =", W1.shape)
print("W1 參數個數 =", W1.size)

print("\nb1 =")
print(b1)
print("b1 shape =", b1.shape)
print("b1 參數個數 =", b1.size)

print("\n第一層總參數個數 =", W1.size + b1.size)

W1 =
[[0.1 0.2 0.3 0.4 0.5]
 [0.2 0.3 0.4 0.5 0.1]
 [0.3 0.4 0.5 0.1 0.2]
 [0.4 0.5 0.1 0.2 0.3]
 [0.5 0.1 0.2 0.3 0.4]
 [0.1 0.3 0.5 0.2 0.4]]
W1 shape = (6, 5)
W1 參數個數 = 30

b1 =
[0.1 0.2 0.1 0.2 0.1]
b1 shape = (5,)
b1 參數個數 = 5

第一層總參數個數 = 35


### 第一隱藏層計算

先計算加權和：z1 = xW1 + b1

再使用 Relu：h1 = Relu(z1)

由於第一隱藏層有 5 個神經元，因此 z1 與 h1 的形狀皆為：(5,)

In [ ]:
# 第一隱藏層的加權和
z1 = np.dot(x, W1) + b1

# Relu
h1 = np.maximum(0, z1)

print("z1 =", z1)
print("z1 shape =", z1.shape)

print("\nh1 = Relu(z1) =", h1)
print("h1 shape =", h1.shape)

z1 = [0.83 1.25 1.27 1.19 1.11]
z1 shape = (5,)

h1 = Relu(z1) = [0.83 1.25 1.27 1.19 1.11]
h1 shape = (5,)


## 第二隱藏層

第二隱藏層共有 4 個神經元，激發函數使用 Relu。

第一隱藏層輸出 5 個神經元，因此：W2 的形狀為：(5, 4)

W2 共有：5 × 4 = 20 個參數

b2 有 4 個參數。

因此第二隱藏層共有：20 + 4 = 24 個參數。

In [ ]:
# 第二隱藏層
# 輸入5個神經元，輸出4個神經元

W2 = np.array([
    [0.2, 0.1, 0.3, 0.4],
    [0.3, 0.2, 0.4, 0.1],
    [0.4, 0.3, 0.1, 0.2],
    [0.1, 0.4, 0.2, 0.3],
    [0.2, 0.3, 0.4, 0.1]
])

b2 = np.array([0.1, 0.2, 0.1, 0.2])

print("W2 =")
print(W2)
print("W2 shape =", W2.shape)
print("W2 參數個數 =", W2.size)

print("\nb2 =")
print(b2)
print("b2 shape =", b2.shape)
print("b2 參數個數 =", b2.size)

print("\n第二層總參數個數 =", W2.size + b2.size)

W2 =
[[0.2 0.1 0.3 0.4]
 [0.3 0.2 0.4 0.1]
 [0.4 0.3 0.1 0.2]
 [0.1 0.4 0.2 0.3]
 [0.2 0.3 0.4 0.1]]
W2 shape = (5, 4)
W2 參數個數 = 20

b2 =
[0.1 0.2 0.1 0.2]
b2 shape = (4,)
b2 參數個數 = 4

第二層總參數個數 = 24


### 第二隱藏層計算

首先計算：z2 = h1W2 + b2

再使用 Relu：h2 = Relu(z2)

因為第二隱藏層有 4 個神經元，所以 z2 與 h2 的形狀都是：(4,)

In [ ]:
# 第二隱藏層的加權和
z2 = np.dot(h1, W2) + b2

# Relu
h2 = np.maximum(0, z2)

print("z2 =", z2)
print("z2 shape =", z2.shape)

print("\nh2 = Relu(z2) =", h2)
print("h2 shape =", h2.shape)

z2 = [1.49  1.723 1.658 1.379]
z2 shape = (4,)

h2 = Relu(z2) = [1.49  1.723 1.658 1.379]
h2 shape = (4,)


## 第三隱藏層

第三隱藏層共有 4 個神經元，激發函數使用 Sigmoid。

因此：W3 的形狀：(4, 4)

W3 共有：4 × 4 = 16 個參數

b3 有：4 個參數

因此第三隱藏層共有：16 + 4 = 20 個參數。

In [ ]:
# 第三隱藏層
# 輸入4個神經元，輸出4個神經元

W3 = np.array([
    [0.2, 0.3, 0.1, 0.4],
    [0.3, 0.4, 0.2, 0.1],
    [0.1, 0.2, 0.4, 0.3],
    [0.4, 0.1, 0.3, 0.2]
])

b3 = np.array([0.1, 0.1, 0.2, 0.1])

print("W3 =")
print(W3)
print("W3 shape =", W3.shape)
print("W3 參數個數 =", W3.size)

print("\nb3 =")
print(b3)
print("b3 shape =", b3.shape)
print("b3 參數個數 =", b3.size)

print("\n第三層總參數個數 =", W3.size + b3.size)

W3 =
[[0.2 0.3 0.1 0.4]
 [0.3 0.4 0.2 0.1]
 [0.1 0.2 0.4 0.3]
 [0.4 0.1 0.3 0.2]]
W3 shape = (4, 4)
W3 參數個數 = 16

b3 =
[0.1 0.1 0.2 0.1]
b3 shape = (4,)
b3 參數個數 = 4

第三層總參數個數 = 20


### 第三隱藏層計算

先計算：z3 = h2W3 + b3

再使用 Sigmoid：h3 = Sigmoid(z3)

Sigmoid 會將數值轉換到 0～1 之間。

第三隱藏層共有 4 個神經元，因此 z3 與 h3 的形狀皆為：(4,)

In [ ]:
# Sigmoid 函數
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# 第三隱藏層的加權和
z3 = np.dot(h2, W3) + b3

# Sigmoid
h3 = sigmoid(z3)

print("z3 =", z3)
print("z3 shape =", z3.shape)

print("\nh3 = Sigmoid(z3) =", h3)
print("h3 shape =", h3.shape)

z3 = [1.6323 1.7057 1.7705 1.6415]
z3 shape = (4,)

h3 = Sigmoid(z3) = [0.83648447 0.84627772 0.85451984 0.83773894]
h3 shape = (4,)


## 輸出層

輸出層共有 3 個神經元，激發函數使用 Softmax。

第三隱藏層輸出 4 個神經元，因此：W4 的形狀：(4, 3)

W4 共有：4 × 3 = 12 個參數

b4 有：3 個參數

因此輸出層共有：12 + 3 = 15 個參數。

In [ ]:
# 輸出層
# 輸入4個神經元，輸出3個神經元

W4 = np.array([
    [0.3, 0.2, 0.1],
    [0.2, 0.4, 0.3],
    [0.1, 0.3, 0.4],
    [0.4, 0.1, 0.2]
])

b4 = np.array([0.1, 0.2, 0.1])

print("W4 =")
print(W4)
print("W4 shape =", W4.shape)
print("W4 參數個數 =", W4.size)

print("\nb4 =")
print(b4)
print("b4 shape =", b4.shape)
print("b4 參數個數 =", b4.size)

print("\n輸出層總參數個數 =", W4.size + b4.size)

W4 =
[[0.3 0.2 0.1]
 [0.2 0.4 0.3]
 [0.1 0.3 0.4]
 [0.4 0.1 0.2]]
W4 shape = (4, 3)
W4 參數個數 = 12

b4 =
[0.1 0.2 0.1]
b4 shape = (3,)
b4 參數個數 = 3

輸出層總參數個數 = 15


### 輸出層計算

首先計算輸出層的加權和：z4 = h3W4 + b4

接著使用 Softmax：y_hat = Softmax(z4)

輸出層共有 3 個神經元，因此：z4 的形狀為：(3,)

y_hat 的形狀為：(3,)

Softmax 的輸出值會介於 0～1 之間，三個類別的機率總和為 1。

因此 y_hat 可以表示 x 屬於第 1、2、3 類別的機率。

In [ ]:
# Softmax 函數
def softmax(x):
    # 減去最大值可以增加數值穩定性
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)


# 輸出層加權和
z4 = np.dot(h3, W4) + b4

# Softmax
y_hat = softmax(z4)

print("z4 =", z4)
print("z4 shape =", z4.shape)

print("\ny_hat =", y_hat)
print("y_hat shape =", y_hat.shape)

print("\ny_hat 總和 =", np.sum(y_hat))

z4 = [0.94074845 1.04593783 0.94688749]
z4 shape = (3,)

y_hat = [0.32081318 0.35639809 0.32278872]
y_hat shape = (3,)

y_hat 總和 = 0.9999999999999999


In [ ]:
print("第一隱藏層")
print("W1 shape =", W1.shape, "參數數量 =", W1.size)
print("b1 shape =", b1.shape, "參數數量 =", b1.size)
print("總參數 =", W1.size + b1.size)

print("\n第二隱藏層")
print("W2 shape =", W2.shape, "參數數量 =", W2.size)
print("b2 shape =", b2.shape, "參數數量 =", b2.size)
print("總參數 =", W2.size + b2.size)

print("\n第三隱藏層")
print("W3 shape =", W3.shape, "參數數量 =", W3.size)
print("b3 shape =", b3.shape, "參數數量 =", b3.size)
print("總參數 =", W3.size + b3.size)

print("\n輸出層")
print("W4 shape =", W4.shape, "參數數量 =", W4.size)
print("b4 shape =", b4.shape, "參數數量 =", b4.size)
print("總參數 =", W4.size + b4.size)

total_parameters = (
    W1.size + b1.size +
    W2.size + b2.size +
    W3.size + b3.size +
    W4.size + b4.size
)

print("\nDNN 總參數數量 =", total_parameters)

第一隱藏層
W1 shape = (6, 5) 參數數量 = 30
b1 shape = (5,) 參數數量 = 5
總參數 = 35

第二隱藏層
W2 shape = (5, 4) 參數數量 = 20
b2 shape = (4,) 參數數量 = 4
總參數 = 24

第三隱藏層
W3 shape = (4, 4) 參數數量 = 16
b3 shape = (4,) 參數數量 = 4
總參數 = 20

輸出層
W4 shape = (4, 3) 參數數量 = 12
b4 shape = (3,) 參數數量 = 3
總參數 = 15

DNN 總參數數量 = 94


In [ ]:
print("\n輸入 x")
print("x =", x)
print("shape =", x.shape)

print("\n第一隱藏層")
print("z1 =", z1)
print("shape =", z1.shape)
print("h1 =", h1)
print("shape =", h1.shape)

print("\n第二隱藏層")
print("z2 =", z2)
print("shape =", z2.shape)
print("h2 =", h2)
print("shape =", h2.shape)

print("\n第三隱藏層")
print("z3 =", z3)
print("shape =", z3.shape)
print("h3 =", h3)
print("shape =", h3.shape)

print("\n輸出層")
print("z4 =", z4)
print("shape =", z4.shape)
print("y_hat =", y_hat)
print("shape =", y_hat.shape)


輸入 x
x = [0.5 0.8 0.3 0.6 0.2 0.9]
shape = (6,)

第一隱藏層
z1 = [0.83 1.25 1.27 1.19 1.11]
shape = (5,)
h1 = [0.83 1.25 1.27 1.19 1.11]
shape = (5,)

第二隱藏層
z2 = [1.49  1.723 1.658 1.379]
shape = (4,)
h2 = [1.49  1.723 1.658 1.379]
shape = (4,)

第三隱藏層
z3 = [1.6323 1.7057 1.7705 1.6415]
shape = (4,)
h3 = [0.83648447 0.84627772 0.85451984 0.83773894]
shape = (4,)

輸出層
z4 = [0.94074845 1.04593783 0.94688749]
shape = (3,)
y_hat = [0.32081318 0.35639809 0.32278872]
shape = (3,)


## 真實答案

題目指定上述輸入資料 x 的真實分類結果為：y = [0, 0, 1]

因此 x 實際上屬於第 3 類別。

In [ ]:
# 真實答案
y = np.array([0, 0, 1])

print("真實答案 y =", y)
print("y shape =", y.shape)

真實答案 y = [0 0 1]
y shape = (3,)


In [ ]:
# Cross Entropy Error
def cross_entropy_error(y, y_hat):
    # 避免 log(0)
    delta = 1e-7
    y_hat = np.clip(y_hat, delta, 1.0 - delta)

    return -np.sum(y * np.log(y_hat))


# 計算誤差
loss = cross_entropy_error(y, y_hat)

print("真實答案 y =", y)
print("預測結果 y_hat =", y_hat)
print("Cross Entropy Error =", loss)

真實答案 y = [0 0 1]
預測結果 y_hat = [0.32081318 0.35639809 0.32278872]
Cross Entropy Error = 1.1307572729305777


## 結果分析

這次使用 NumPy 來模擬一個多隱藏層的全連接神經網路。

神經網路的架構為：6 → 5 → 4 → 4 → 3

各層使用的激活函數如下：

* 第一隱藏層使用 Relu
* 第二隱藏層使用 Relu
* 第三隱藏層使用 Sigmoid
* 輸出層使用 Softmax

將輸入資料經過 Forward Propagation 計算後，可以得到預測結果 y_hat。

y_hat裡面有 3 個數值，分別代表輸入資料 x 被預測為第 1、2、3 類別的機率，而這 3 個機率加起來會等於 1。

這題的正確答案是：y = [0, 0, 1]

表示這筆資料實際上是屬於第 3 類別。

最後再使用 Cross Entropy Error來計算預測結果 y_hat 和實際答案 y 之間的差異。一般來說，Cross Entropy Error 越小，就代表模型預測得越接近正確答案。


## HW1-2. 將全連接神經網路設計為函數

這一題是接著第 1 題的全連接神經網路（DNN）來做。

第 1 題是一步一步進行神經網路的計算，這一題則是把前面的計算過程整理成一個 dnn 函數。只要輸入資料 x，函數就會依照原本的神經網路架構進行計算，最後得到預測結果 y_hat。

這一題使用的權重 W、偏值 b 和激發函數，都跟第 1 題相同。

In [38]:
def dnn(x):
    # 第一隱藏層
    z1 = np.dot(x, W1) + b1
    h1 = np.maximum(0, z1)   # Relu

    # 第二隱藏層
    z2 = np.dot(h1, W2) + b2
    h2 = np.maximum(0, z2)   # Relu

    # 第三隱藏層
    z3 = np.dot(h2, W3) + b3
    h3 = sigmoid(z3)       # Sigmoid

    # 輸出層
    z4 = np.dot(h3, W4) + b4
    y_hat = softmax(z4)     # Softmax

    return y_hat

## 1. 使用第 1 題的輸入資料進行測試

將第 1 題所使用的 x 輸入 dnn 函數，觀察函數輸出的 y_hat。

In [39]:
# 使用第1題相同的x
y_hat_dnn = dnn(x)

print("第 1 題的 y_hat：")
print(y_hat)

print("\ndnn(x) 的 y_hat：")
print(y_hat_dnn)

第 1 題的 y_hat：
[0.32081318 0.35639809 0.32278872]

dnn(x) 的 y_hat：
[0.32081318 0.35639809 0.32278872]


In [40]:
# 比較兩個結果是否相同
print("兩個結果是否相同：", np.allclose(y_hat, y_hat_dnn))

兩個結果是否相同： True


In [41]:
print("第 1 題 y_hat =", y_hat)
print("第 2 題 dnn(x) =", y_hat_dnn)

if np.allclose(y_hat, y_hat_dnn):
    print("結果相同")
else:
    print("結果不同")

第 1 題 y_hat = [0.32081318 0.35639809 0.32278872]
第 2 題 dnn(x) = [0.32081318 0.35639809 0.32278872]
結果相同


## 2. 結果比較

把第 1 題的輸入資料 x 放進 dnn 函數後，可以得到 y_hat。

將這次得到的 y_hat 和第 1 題直接計算出來的結果比較後，兩個結果是一樣的。

主要是因為 dnn 函數裡面的權重 W1、W2、W3、W4，以及偏值 b1、b2、b3、b4，都跟第 1 題使用的一樣，激發函數也沒有改變。

所以雖然這次是把計算過程寫成 dnn 函數，但最後算出來的結果還是會和第 1 題相同。

## 安裝 Gradio

In [42]:
!pip install -q gradio

## 建立 Gradio 使用的函數

In [43]:
def predict_class(x1, x2, x3, x4, x5, x6):
    # 將輸入的 6 個特徵值組合成 x
    x_input = np.array([x1, x2, x3, x4, x5, x6])

    # 使用 dnn 計算 y_hat
    y_hat = dnn(x_input)

    # 找出機率最大的類別
    class_index = np.argmax(y_hat)

    # Python 索引從 0 開始，所以 +1
    predicted_class = class_index + 1

    return predicted_class

In [44]:
np.argmax(y_hat)

np.int64(1)

In [45]:
import gradio as gr

demo = gr.Interface(
    fn=predict_class,
    inputs=[
        gr.Number(label="特徵值 x1"),
        gr.Number(label="特徵值 x2"),
        gr.Number(label="特徵值 x3"),
        gr.Number(label="特徵值 x4"),
        gr.Number(label="特徵值 x5"),
        gr.Number(label="特徵值 x6")
    ],
    outputs=gr.Number(label="預測類別"),
    title="dnn 類別預測",
    description="請輸入 6 個特徵值，系統會利用 dnn 預測第 1、2 或第 3 類別。"
)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://025347471c4fe1cc32.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
